#!/bin/bash

echo "🔧 Applying BEP 9 Metadata Extension Fix..."

# Backup the original file
cp /Users/richardbrown/dev/dht_crawler/src/dht_crawler.cpp /Users/richardbrown/dev/dht_crawler/src/dht_crawler.cpp.backup

echo "✅ Backup created: dht_crawler.cpp.backup"

echo ""
echo "🛠️  MANUAL STEPS TO APPLY THE FIX:"
echo ""
echo "1. Edit /Users/richardbrown/dev/dht_crawler/src/dht_crawler.cpp"
echo ""
echo "2. Find this section (around line 600-650):"
echo "   lt::session_params params;"
echo "   lt::settings_pack& settings = params.settings;"
echo ""
echo "3. Replace the entire settings configuration block with:"
echo ""
echo "   // *** FIXED SESSION CONFIGURATION FOR BEP 9 METADATA EXCHANGE ***"
echo "   lt::session_params params;"
echo "   lt::settings_pack& settings = params.settings;"
echo ""
echo "   // *** CRITICAL: Enable metadata extension (BEP 9) ***"
echo "   settings.set_bool(lt::settings_pack::enable_extensions, true);"
echo ""
echo "   // DHT configuration"  
echo "   settings.set_bool(lt::settings_pack::enable_dht, true);"
echo "   settings.set_int(lt::settings_pack::dht_announce_interval, 15);"
echo ""
echo "   // *** FIXED: Extended alert mask for metadata ***"
echo "   settings.set_int(lt::settings_pack::alert_mask,"
echo "       lt::alert_category::dht |"
echo "       lt::alert_category::peer |"
echo "       lt::alert_category::status |"
echo "       lt::alert_category::connect |"
echo "       lt::alert_category::error |"
echo "       lt::alert_category::torrent);"
echo ""
echo "   // Port binding"
echo "   settings.set_str(lt::settings_pack::listen_interfaces, \"0.0.0.0:6881\");"
echo ""
echo "   // *** FIXED: Longer timeouts for metadata exchange ***"
echo "   settings.set_int(lt::settings_pack::handshake_timeout, 30);"
echo "   settings.set_int(lt::settings_pack::peer_timeout, 180);"
echo ""
echo "   // Connection settings"
echo "   settings.set_bool(lt::settings_pack::enable_lsd, true);"
echo "   settings.set_bool(lt::settings_pack::enable_peer_exchange, true);"
echo "   settings.set_int(lt::settings_pack::connections_limit, 200);"
echo "   settings.set_int(lt::settings_pack::active_limit, 1000);"
echo ""
echo "   // *** CRITICAL: Enable TCP for metadata exchange ***"
echo "   settings.set_bool(lt::settings_pack::enable_outgoing_utp, true);"
echo "   settings.set_bool(lt::settings_pack::enable_incoming_utp, true);"
echo "   settings.set_bool(lt::settings_pack::enable_outgoing_tcp, true);"
echo "   settings.set_bool(lt::settings_pack::enable_incoming_tcp, true);"
echo ""
echo "   // Port forwarding"
echo "   settings.set_bool(lt::settings_pack::enable_upnp, true);"
echo "   settings.set_bool(lt::settings_pack::enable_natpmp, true);"
echo ""
echo "4. Save the file"
echo ""
echo "5. Rebuild:"
echo "   cd /Users/richardbrown/dev/dht_crawler"
echo "   make clean"
echo "   make release-macos-arm"
echo ""
echo "6. Test with:"
echo "   ./builds/macos/arm/Release/dht_crawler --metadata /Users/richardbrown/dev/dht_crawler/ubuntu_test.txt --debug --metadata_log"
echo ""
echo "🎯 EXPECTED RESULT:"
echo "   Instead of peer timeouts, you should see:"
echo "   '[METADATA_LOG] *** METADATA DISCOVERED ***'"
echo ""
echo "The key changes:"
echo "✅ Enable extensions (BEP 9 metadata protocol)"
echo "✅ Longer timeouts (30s handshake, 180s peer timeout)"
echo "✅ Enable TCP connections (critical for metadata)"
echo "✅ Enable peer exchange for better peer discovery"
